name: Go CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
          args: --timeout=2m  # Переопределяем timeout из конфига для CI         
      
      - run: go mod tidy
      
      -  run: golangci-lint run ./...

      - run: go test ./...
      
      - run: go build -v ./...