name: Go CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH          
      - run: go mod tidy
      

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - run: go test ./...
      - run: go build -v ./...